# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nuz15FB8wTeLIGZ75wIps4sYttPXEmHh
"""

import pandas as pd
import numpy as np

#Carregar o arquivo
pedidos = pd.read_csv("/content/pedidos.csv")

#Visualizar os primeiros registros
pedidos.head()

#Visualizar os últimos registros
pedidos.tail()

#Estrutura geral do DataFrame
pedidos.info()

#Estatísticas descritivas
pedidos.describe()

pedidos.head()

#Criação de Nova Coluna (Feature Engineering)
pedidos["Receita_total"] = pedidos["Quantidade"] * pedidos["Preco_Unitario"]
pedidos.head()

#Verificar se existe Valores Ausentes
pedidos.info()

#Verificar se existe Valores Ausentes
pedidos.isna().sum()

# Preencher valores nulos em Quantidade com a média
pedidos["Quantidade"].fillna(pedidos["Quantidade"].mean(), inplace=True)

pedidos.info()

#Remover linhas com preço unitário nulo
pedidos.dropna(subset=["Preco_Unitario"], inplace=True)

pedidos.info()

pedidos.head()

#Quantidade total e receita total por item - Agrupando
resumo_itens = pedidos.groupby("Item")[["Quantidade", "Receita_total"]].sum().reset_index()

print(pedidos.groupby("Item")[["Quantidade", "Receita_total"]].sum().reset_index())

#Top 5 itens mais vendidos (quantidade)
top_5_quantidade = resumo_itens.sort_values(
    by="Quantidade", ascending=False
).head(5)

print(top_5_quantidade)

#Top 5 itens que mais geraram receita
top_5_receita = resumo_itens.sort_values(
    by="Receita_total", ascending=False
).head(5)

print(top_5_receita)

#Converter a coluna de data - Análise Temporal
pedidos["Data"] = pd.to_datetime(pedidos["Data"])
print(pedidos.info())

#Extrair o mês do pedido
pedidos["Mes"] = pedidos["Data"].dt.to_period("M")
print(pedidos.head())

#Receita total por mês
receita_mensal = pedidos.groupby("Mes")["Receita_total"].sum()
print(receita_mensal)

#Upload do cardápio
cardapio = pd.read_csv("/content/cardapio.csv")
print(cardapio.head())

#Merge entre pedidos e cardápio
pedidos_completo = pedidos.merge(
    cardapio,
    left_on="Item",
    right_on="Item",
    how="inner"
)
print(pedidos_completo.head())

#Receita por categoria
receita_mensal_categoria = pedidos_completo.groupby(["Mes", "Categoria"])["Receita_total"].sum()
print(receita_mensal_categoria)

#Categoria gera mais receita
categoria_mais_receita = receita_mensal_categoria.idxmax()
print(categoria_mais_receita)

#Filtros e Consultas - Salgados com quantidade superior a 10 unidades
filtro_salgados = pedidos_completo[
    (pedidos_completo["Categoria"] =="Salgados") &
    (pedidos_completo["Quantidade"] >10)
]

filtro_salgados

#KPIs do Negócio - Receita total
receita_total = pedidos_completo["Receita_total"].sum()
print(receita_total)

#Total de itens vendidos
total_itens_vendidos = np.sum(pedidos["Quantidade"])
print(total_itens_vendidos)

#Ticket médio
ticket_medio = receita_total / pedidos.shape[0]
print(ticket_medio)